#!/usr/bin/env node
// Generates src/lib/psl-data.js from the canonical Public Suffix List.
// Runtime extension code stays fully local; this maintainer script is run only when updating data.

import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { domainToASCII } from 'node:url';

const CANONICAL_URL = 'https://publicsuffix.org/list/public_suffix_list.dat';
const SNAPSHOT_PATH = 'third_party/publicsuffix/public_suffix_list.dat';
const OUTPUT_PATH = 'src/lib/psl-data.js';
const CHECK_ONLY = process.argv.includes('--check');

async function readSource() {
  if (CHECK_ONLY) return readFileSync(SNAPSHOT_PATH, 'utf8');
  const response = await fetch(CANONICAL_URL, {
    redirect: 'follow',
    signal: AbortSignal.timeout(15_000)
  });
  if (!response.ok) {
    throw new Error(`PSL download failed with HTTP ${response.status}`);
  }
  if (new URL(response.url).hostname !== 'publicsuffix.org') {
    throw new Error(`PSL download redirected to unexpected host: ${response.url}`);
  }
  return response.text();
}

function asciiRule(value) {
  const ascii = domainToASCII(value.trim().toLowerCase());
  if (!ascii) throw new Error(`Invalid PSL rule: ${value}`);
  return ascii;
}

function formatList(name, values) {
  const lines = values.map((value) => `  ${JSON.stringify(value)}`);
  return `export const ${name} = Object.freeze([\n${lines.join(',\n')}\n]);`;
}

const raw = await readSource();
if (raw.length < 100_000 || raw.length > 2_000_000) {
  throw new Error(`Unexpected PSL size: ${raw.length} bytes`);
}
for (const marker of [
  '===BEGIN ICANN DOMAINS===',
  '===END ICANN DOMAINS===',
  '===BEGIN PRIVATE DOMAINS===',
  '===END PRIVATE DOMAINS==='
]) {
  if (!raw.includes(marker)) throw new Error(`PSL marker is missing: ${marker}`);
}

const version = raw.match(/^\/\/ VERSION: ([^\r\n]+)/m)?.[1] || 'unknown';
const commit = raw.match(/^\/\/ COMMIT: ([^\r\n]+)/m)?.[1] || 'unknown';
if (version === 'unknown' || commit === 'unknown') {
  throw new Error('PSL VERSION or COMMIT metadata is missing');
}

const normal = new Set();
const wildcard = new Set();
const exception = new Set();

for (const sourceLine of raw.split(/\r?\n/)) {
  const line = sourceLine.trim();
  if (!line || line.startsWith('//')) continue;
  if (line.startsWith('!')) {
    exception.add(asciiRule(line.slice(1)));
  } else if (line.startsWith('*.')) {
    wildcard.add(asciiRule(line.slice(2)));
  } else {
    normal.add(asciiRule(line));
  }
}

if (normal.size < 9_000 || wildcard.size < 200 || exception.size < 5) {
  throw new Error(
    `PSL rule counts are unexpectedly low: ${normal.size}/${wildcard.size}/${exception.size}`
  );
}

const sort = (values) => [...values].sort();
const sourceSha256 = createHash('sha256').update(raw).digest('hex');
const output = `// SPDX-License-Identifier: MPL-2.0
// Generated by scripts/update-psl.mjs from ${CANONICAL_URL}
// Source version: ${version}
// Source commit: ${commit}
// Source SHA-256: ${sourceSha256}
// Rules: ${normal.size} normal, ${wildcard.size} wildcard, ${exception.size} exception
// Do not edit this file manually; run: node scripts/update-psl.mjs

export const PSL_VERSION = ${JSON.stringify(version)};

${formatList('PUBLIC_SUFFIXES', sort(normal))}

${formatList('WILDCARD_SUFFIXES', sort(wildcard))}

${formatList('EXCEPTION_SUFFIXES', sort(exception))}
`;

if (CHECK_ONLY) {
  if (readFileSync(OUTPUT_PATH, 'utf8') !== output) {
    throw new Error(`${OUTPUT_PATH} is out of date; run node scripts/update-psl.mjs`);
  }
  console.log(`${OUTPUT_PATH} matches the vendored PSL snapshot (${version}, ${commit}).`);
  process.exit(0);
}

mkdirSync('third_party/publicsuffix', { recursive: true });
writeFileSync(SNAPSHOT_PATH, raw);
writeFileSync(OUTPUT_PATH, output);
console.log(
  `Updated ${SNAPSHOT_PATH} and ${OUTPUT_PATH}: ${normal.size} normal, ` +
  `${wildcard.size} wildcard, ${exception.size} exception rules (${version}, ${commit}).`
);
